//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int Bitacora_Id { get; set; }
        public string BitacoraDescripcion { get; set; }
        public Nullable<System.DateTime> BitacoraFecha { get; set; }
        public int UsuarioId { get; set; }
        public int CierreDia_Id { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual CierreDias CierreDias { get; set; }
    }
}
