//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreDia
    {
        public int CierreDiaId { get; set; }
        public decimal CierreDiaTotal { get; set; }
        public System.DateTime CierreDiaFecha { get; set; }
        public int SemanaId { get; set; }
    
        public virtual Semana Semana { get; set; }
    }
}
