//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cierres
    {
        public int Cierre_Id { get; set; }
        public Nullable<decimal> CierreTotal { get; set; }
        public Nullable<System.DateTime> CierreFechaInicial { get; set; }
        public Nullable<System.DateTime> CierreFechaFinal { get; set; }
        public int CajaId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> CierreFecha { get; set; }
        public string TipoCierre { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
