//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depositos
    {
        public int Deposito_Id { get; set; }
        public Nullable<decimal> DepositoSaldoTotal { get; set; }
        public string DepositoDescripcion { get; set; }
        public Nullable<System.DateTime> DepositoFecha { get; set; }
        public Nullable<int> DepositoCantidadUnlps { get; set; }
        public Nullable<int> DepositoCantidadDoslps { get; set; }
        public Nullable<int> DepositoCantidadCincolps { get; set; }
        public Nullable<int> DepositoCantidadDiezlps { get; set; }
        public Nullable<int> DepositoCantidadVeintelps { get; set; }
        public Nullable<int> DepositoCantidadCincuentalps { get; set; }
        public Nullable<int> DepositoCantidadCienlps { get; set; }
        public Nullable<int> DepositoCantidadDoscientoslps { get; set; }
        public Nullable<int> DepositoCantidadQuinientos { get; set; }
        public Nullable<int> DepositoCantidadCincocent { get; set; }
        public Nullable<int> DepositoCantidadDiezcent { get; set; }
        public Nullable<int> DepositoCantidadVeintecent { get; set; }
        public Nullable<int> DepositoCantidadCincuentacent { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> CajaId { get; set; }
        public Nullable<int> SaldoInicial_Id { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual SaldosIniciales SaldosIniciales { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
