//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlujoDeCajaEntities : DbContext
    {
        public FlujoDeCajaEntities()
            : base("name=FlujoDeCajaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<CierreDias> CierreDias { get; set; }
        public virtual DbSet<SaldosIniciales> SaldosIniciales { get; set; }
        public virtual DbSet<Cierres> Cierres { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
