//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retiros
    {
        public int Retiro_Id { get; set; }
        public Nullable<decimal> RetiroSaldoTotal { get; set; }
        public string RetiroDescripcion { get; set; }
        public Nullable<System.DateTime> RetiroFecha { get; set; }
        public Nullable<int> RetiroCantidadUnlps { get; set; }
        public Nullable<int> RetiroCantidadDoslps { get; set; }
        public Nullable<int> RetiroCantidadCincolps { get; set; }
        public Nullable<int> RetiroCantidadDiezlps { get; set; }
        public Nullable<int> RetiroCantidadVeintelps { get; set; }
        public Nullable<int> RetiroCantidadCincuentalps { get; set; }
        public Nullable<int> RetiroCantidadCienlps { get; set; }
        public Nullable<int> RetiroCantidadDoscientoslps { get; set; }
        public Nullable<int> RetiroCantidadQuinientos { get; set; }
        public Nullable<int> RetiroCantidadCincocent { get; set; }
        public Nullable<int> RetiroCantidadDiezcent { get; set; }
        public Nullable<int> RetiroCantidadVeintecent { get; set; }
        public Nullable<int> RetiroCantidadCincuentacent { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> CajaId { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
