//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionDetalle
    {
        public int TransaccionDetalleId { get; set; }
        public int TransaccionId { get; set; }
        public string Saldo { get; set; }
        public string Tipo { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
    }
}
