//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_TornillosDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.TransaccionDetalle = new HashSet<TransaccionDetalle>();
        }
    
        public int TransaccionId { get; set; }
        public int UsuarioId { get; set; }
        public int CajaId { get; set; }
        public int DiaId { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual Semana Semana { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionDetalle> TransaccionDetalle { get; set; }
    }
}
